version: "3.7"

services:
  node:
    container_name: dashboard_api
    image: node:10.14.0-alpine
    working_dir: /home/node/app
    ports:
      - "5050:8081"
    volumes:
      - "./src:/home/node/app/src"
      - "./test:/home/node/app/test"
      - "./package.json:/home/node/app/package.json"
      - "./tsconfig.json:/home/node/app/tsconfig.json"
      - "./node_modules:/home/node/app/node_modules"

    command: "yarn start"