version: "3.7"

services:
  node:
    container_name: dev_api
    image: node:10.14.0-alpine
    working_dir: /home/node/app/
    ports:
      - 8081:8081
    volumes:
      - "./src:/home/node/app/src"
      - "./development:/home/node/app/development"
      - "./package.json:/home/node/app/package.json"
      - "./node_modules:/home/node/app/node_modules"
      - "./tsconfig.json:/home/node/app/tsconfig.json"
      - "./nodemon.json:/home/node/app/nodemon.json"
    command: "yarn start"

  mongo:
    container_name: dev_mongo
    image: mongo:4.0.4-xenial
    restart: always
    ports:
      - 27017:27017
