version: "3.7"

services:
  node:
    container_name: BEST_api_node
    image: node:12-alpine
    working_dir: /home/node/app/
    ports:
      - 8081:8081
    volumes:
      - ./src:/home/node/app/src
      - ./package.json:/home/node/app/package.json
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./node_modules:/home/node/app/node_modules
      - ./development:/home/node/app/development
    tty: true
    command: yarn run nodemon

  db:
    container_name: BEST_api_postgres
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bestbrasov
    volumes:
      - ./development/db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  redis:
    container_name: BEST_api_cache
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379